USE MRL 
GO
IF OBJECT_ID('BAD.SP_GET_ALL_ACCOUNTS') IS NOT NULL
    BEGIN
        DROP PROCEDURE BAD.SP_GET_ALL_ACCOUNTS
    END
GO
CREATE PROCEDURE BAD.SP_GET_ALL_ACCOUNTS
AS
BEGIN
    SELECT * FROM BAD.ACCOUNTS
END